#!/usr/bin/env bash
# bundle-python.sh — download portable, offline CPython builds from
# astral-sh/python-build-standalone and write them into python/ with the
# canonical names, then regenerate python/checksums.sha256.
#
# Mirrors scripts/internal/bundle-rust-toolchain.sh: run ONCE on any machine
# with internet access. The resulting archives in python/ are committed to git
# so ci/jenkins/setup-python.sh can bootstrap a Python interpreter on fully
# air-gapped agents with no system Python.
#
# Both archives are the install_only_stripped variant (smallest self-contained
# build) and stay under 45 MB, so — unlike the Rust toolchain / vendor archives
# — they are NOT split into parts.
#
# Usage:
#   bash ci/jenkins/bundle-python.sh                    # defaults below
#   RELEASE=20260807 PYVER=3.14.7 bash ci/jenkins/bundle-python.sh
#
# Requirements: bash, curl, gzip, tar, sha256sum
set -euo pipefail

# ── Parameters (override via environment) ─────────────────────────────────────
RELEASE="${RELEASE:-20260807}"   # python-build-standalone release tag (date)
PYVER="${PYVER:-3.14.7}"         # CPython version within that release
VARIANT="install_only_stripped"  # smallest self-contained layout

# MINOR is used for the committed archive name (e.g. 3.14) — matches the
# toolchain/ convention of naming by feature version, not patch level.
MINOR="$(printf '%s' "${PYVER}" | cut -d. -f1-2)"

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
PYTHON_DIR="$REPO_ROOT/python"

BASE_URL="https://github.com/astral-sh/python-build-standalone/releases/download/${RELEASE}"

echo "python-build-standalone release: ${RELEASE}  CPython: ${PYVER}  variant: ${VARIANT}"

# ── Platform table: <local archive name> <upstream rust-style target> ────────
# Upstream asset name: cpython-<PYVER>+<RELEASE>-<target>-<VARIANT>.tar.gz
download_one() {
    local output_name="$1"
    local target="$2"

    local asset="cpython-${PYVER}%2B${RELEASE}-${target}-${VARIANT}.tar.gz"
    local url="${BASE_URL}/${asset}"
    local output="${PYTHON_DIR}/${output_name}"

    echo ""
    echo "=== Downloading ${output_name} (${target}) ==="
    echo "  ${url}"
    curl -L --fail --connect-timeout 30 "${url}" -o "${output}"

    # Sanity: valid gzip and the expected top-level python/ layout.
    if ! gzip -t "${output}"; then
        echo "[ERROR] ${output_name} is not a valid gzip archive." >&2
        return 1
    fi
    if ! tar -tzf "${output}" | grep -qE '^python/'; then
        echo "[ERROR] ${output_name} does not contain a top-level python/ tree." >&2
        return 1
    fi

    local out_size_mb
    out_size_mb="$(du -sm "${output}" | awk '{print $1}')"
    echo "  [OK] ${output_name} — ${out_size_mb} MB"
}

# ── Run ───────────────────────────────────────────────────────────────────────
mkdir -p "$PYTHON_DIR"

download_one "cpython-${MINOR}-windows-x64.tar.gz"  "x86_64-pc-windows-msvc"
download_one "cpython-${MINOR}-linux-x86_64.tar.gz" "x86_64-unknown-linux-gnu"

# ── Regenerate checksums.sha256 ──────────────────────────────────────────────
echo ""
echo "Regenerating python/checksums.sha256..."
CHECKSUMS="$PYTHON_DIR/checksums.sha256"
{
    printf '# oxide-sloc portable Python checksums\n'
    printf '# Generated by ci/jenkins/bundle-python.sh\n'
    printf '# CPython %s (%s) from astral-sh/python-build-standalone, %s\n' "$PYVER" "$RELEASE" "$VARIANT"
    printf '# Verify with: sha256sum -c python/checksums.sha256\n\n'
    for f in "$PYTHON_DIR"/cpython-*.tar.gz; do
        [[ -f "$f" ]] && printf '%s  python/%s\n' \
            "$(sha256sum "$f" | awk '{print $1}')" "$(basename "$f")"
    done
} > "$CHECKSUMS"
cat "$CHECKSUMS"

echo ""
echo "Done. Commit the results:"
echo ""
echo "  git add python/"
echo "  git commit -m \"chore: update bundled Python\""
echo "  git push"
echo ""
echo "Any 'git clone' of the repo will include the Python archives."
echo "ci/jenkins/setup-python.sh reassembles them on an offline agent."
