#!/usr/bin/env bash
# bundle-rust-toolchain.sh — download and stage a standalone Rust toolchain installer
# tarball into toolchain/ so that install.sh can bootstrap Rust on a machine with no
# internet access and no pre-installed Rust toolchain.
#
# Run this script ONCE on any machine that has internet access. The resulting
# toolchain/ archives must be committed via git LFS (they are ~170-250 MB each):
#
#   git lfs install                 # run once per machine if not already configured
#   git add toolchain/
#   git commit -m "chore: bundle Rust toolchain for offline builds vX.Y.Z"
#   git push
#
# After that, any fresh git clone (with LFS) includes the toolchain. Running
# bash scripts/install.sh on a machine with no Rust will auto-bootstrap it.
#
# Usage:
#   bash scripts/internal/bundle-rust-toolchain.sh              # host platform
#   bash scripts/internal/bundle-rust-toolchain.sh windows-x64
#   bash scripts/internal/bundle-rust-toolchain.sh linux-x86_64
#   bash scripts/internal/bundle-rust-toolchain.sh linux-arm64
#
# Requirements: bash, curl, sha256sum, xargs (standard on Git Bash and Linux).
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
TOOLCHAIN_DIR="$REPO_ROOT/toolchain"
RUST_DIST_BASE="https://static.rust-lang.org/dist"

# ── Read pinned Rust version from rust-toolchain.toml ───────────────────────
TOOLCHAIN_TOML="$REPO_ROOT/rust-toolchain.toml"
if [[ ! -f "$TOOLCHAIN_TOML" ]]; then
    echo "[ERROR] rust-toolchain.toml not found at $TOOLCHAIN_TOML" >&2
    exit 1
fi
CHANNEL="$(grep 'channel' "$TOOLCHAIN_TOML" | sed 's/.*= *"\(.*\)"/\1/')"
# Expand "1.95" → "1.95.0"; leave "stable" / "nightly" as-is for URL
case "$CHANNEL" in
    stable|nightly|beta) RUST_VER="$CHANNEL" ;;
    *.*.*)               RUST_VER="$CHANNEL" ;;         # already X.Y.Z
    *.*)                 RUST_VER="${CHANNEL}.0" ;;      # X.Y → X.Y.0
    *)                   RUST_VER="$CHANNEL" ;;
esac
echo "Rust channel: $CHANNEL  (download version: $RUST_VER)"

# ── Resolve target platform ──────────────────────────────────────────────────
PLATFORM_ARG="${1:-}"
if [[ -z "$PLATFORM_ARG" ]]; then
    # Auto-detect host
    if [[ -n "${WINDIR+x}" ]] || [[ "${OSTYPE:-}" == msys* ]] || [[ "${OSTYPE:-}" == cygwin* ]]; then
        PLATFORM_ARG="windows-x64"
    else
        case "$(uname -m 2>/dev/null)" in
            aarch64|arm64) PLATFORM_ARG="linux-arm64"   ;;
            *)             PLATFORM_ARG="linux-x86_64"  ;;
        esac
    fi
    echo "Auto-detected platform: $PLATFORM_ARG"
fi

case "$PLATFORM_ARG" in
    windows-x64)    RUST_TARGET="x86_64-pc-windows-gnu"    OUTPUT_NAME="rust-toolchain-windows-x64.tar.gz"    ;;
    linux-x86_64)   RUST_TARGET="x86_64-unknown-linux-gnu" OUTPUT_NAME="rust-toolchain-linux-x86_64.tar.gz"   ;;
    linux-arm64)    RUST_TARGET="aarch64-unknown-linux-gnu" OUTPUT_NAME="rust-toolchain-linux-arm64.tar.gz"    ;;
    *)
        echo "[ERROR] Unknown platform '$PLATFORM_ARG'." >&2
        echo "  Supported: windows-x64  linux-x86_64  linux-arm64" >&2
        exit 1
        ;;
esac

# ── Download ─────────────────────────────────────────────────────────────────
mkdir -p "$TOOLCHAIN_DIR"

SRC_ARCHIVE="rust-${RUST_VER}-${RUST_TARGET}.tar.gz"
SRC_URL="$RUST_DIST_BASE/$SRC_ARCHIVE"
SHA_URL="$RUST_DIST_BASE/${SRC_ARCHIVE}.sha256"
DEST="$TOOLCHAIN_DIR/$OUTPUT_NAME"
SHA_TMP="$(mktemp)"

echo ""
echo "Downloading $SRC_ARCHIVE..."
echo "  URL: $SRC_URL"
if ! curl -fSL --progress-bar --connect-timeout 30 --max-time 600 -o "$DEST" "$SRC_URL"; then
    echo "[ERROR] Download failed: $SRC_URL" >&2
    rm -f "$DEST" "$SHA_TMP"
    exit 1
fi

echo "Verifying checksum..."
if curl -fsSL --connect-timeout 10 --max-time 30 -o "$SHA_TMP" "$SHA_URL" 2>/dev/null; then
    EXPECTED="$(awk '{print $1}' "$SHA_TMP")"
    ACTUAL="$(sha256sum "$DEST" | awk '{print $1}')"
    rm -f "$SHA_TMP"
    if [[ "$EXPECTED" != "$ACTUAL" ]]; then
        echo "[ERROR] Checksum mismatch for $SRC_ARCHIVE" >&2
        echo "  Expected: $EXPECTED" >&2
        echo "  Actual:   $ACTUAL" >&2
        rm -f "$DEST"
        exit 1
    fi
    echo "  [OK] Checksum verified: $EXPECTED"
else
    rm -f "$SHA_TMP"
    echo "  [WARN] Could not fetch .sha256 sidecar — skipping verification."
fi

# ── Update toolchain/checksums.sha256 ────────────────────────────────────────
echo ""
echo "Regenerating toolchain/checksums.sha256..."
CHECKSUMS="$TOOLCHAIN_DIR/checksums.sha256"
{
    printf '# oxide-sloc Rust toolchain checksums\n'
    printf '# Generated by scripts/internal/bundle-rust-toolchain.sh\n'
    printf '# Rust %s — used by install.sh to bootstrap offline builds\n' "$RUST_VER"
    printf '# Verify with: sha256sum -c toolchain/checksums.sha256\n\n'
    for f in "$TOOLCHAIN_DIR"/rust-toolchain-*.tar.gz 2>/dev/null; do
        [[ -f "$f" ]] && sha256sum "$f"
    done
} > "$CHECKSUMS"
cat "$CHECKSUMS"

# ── Print next steps ──────────────────────────────────────────────────────────
ARCHIVE_SIZE_MB="$(du -m "$DEST" | awk '{print $1}')"
echo ""
echo "[OK] $OUTPUT_NAME  (${ARCHIVE_SIZE_MB} MB)"
echo ""
echo "This archive exceeds GitHub's 100 MB file limit."
echo "Commit it via git LFS:"
echo ""
echo "  git lfs install                 # run once per machine if not already done"
echo "  git add toolchain/"
echo "  git commit -m \"chore: bundle Rust toolchain for offline builds\""
echo "  git push"
echo ""
echo "After pushing, any 'git clone' (with LFS) will include the toolchain."
echo "Running 'bash scripts/install.sh' on a no-Rust machine will bootstrap"
echo "Rust from the bundle and build oxide-sloc from vendor sources."
