#!/usr/bin/env bash
# update-dist.sh — build and stage pre-built binaries into dist/ for commit.
#
# Run this on any machine with the appropriate Rust toolchain before tagging a release.
# After it completes, commit the results:
#
#   git add dist/
#   git commit -m "chore: update pre-built binaries vX.Y.Z"
#
# For cross-compiled targets (e.g. linux-arm64 from an x86_64 host), install the
# cross-compilation target first:
#   rustup target add aarch64-unknown-linux-musl
# and ensure a suitable linker is available (musl-cross or cross).
#
# Usage:
#   bash scripts/internal/update-dist.sh                    # build for current host
#   bash scripts/internal/update-dist.sh --windows-only     # package only Windows binary
#   bash scripts/internal/update-dist.sh --linux-only       # build only Linux binary
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
DIST="$REPO_ROOT/dist"

WINDOWS_ONLY=false
LINUX_ONLY=false
for arg in "$@"; do
    case "$arg" in
        --windows-only) WINDOWS_ONLY=true ;;
        --linux-only)   LINUX_ONLY=true   ;;
    esac
done

mkdir -p "$DIST"

# Detect version from workspace Cargo.toml
VERSION="$(grep -m1 '^version = ' "$REPO_ROOT/Cargo.toml" | sed 's/version = "\(.*\)"/\1/')"
echo "oxide-sloc version: $VERSION"

# ── Windows binary ───────────────────────────────────────────────────────────
if [[ "$LINUX_ONLY" == false ]]; then
    if [[ -n "${WINDIR+x}" ]] || [[ "${OSTYPE:-}" == msys* ]] || [[ "${OSTYPE:-}" == cygwin* ]]; then
        echo "Building Windows release binary..."
        cd "$REPO_ROOT"

        # Ensure vendor sources are extracted
        if [[ ! -d vendor ]]; then
            echo "  Extracting vendor.tar.xz..."
            tar -xJf vendor.tar.xz
        fi
        mkdir -p .cargo
        cat > .cargo/config.toml <<'EOF'
[source.crates-io]
replace-with = "vendored-sources"

[source.vendored-sources]
directory = "vendor"
EOF
        cargo build --release --offline -p oxide-sloc

        echo "  Packaging dist/oxide-sloc-windows-x64.zip..."
        WIN_EXE="$(cygpath -w "$REPO_ROOT/target/release/oxide-sloc.exe")"
        WIN_DIST="$(cygpath -w "$DIST/oxide-sloc-windows-x64.zip")"
        powershell -NoProfile -Command "
            \$src = '$WIN_EXE'
            \$dst = '$WIN_DIST'
            if (Test-Path \$dst) { Remove-Item \$dst -Force }
            Compress-Archive -Path \$src -DestinationPath \$dst
            Write-Host '  Done.'
        "
        # Also copy to repo root for convenience (install.sh checks here first)
        cp "target/release/oxide-sloc.exe" oxide-sloc.exe
        echo "  [OK] dist/oxide-sloc-windows-x64.zip"
    else
        echo "  Skipping Windows binary (not on Windows; use a Windows host or cross-compile)"
    fi
fi

# ── Linux binary ─────────────────────────────────────────────────────────────
if [[ "$WINDOWS_ONLY" == false ]]; then
    OSTYPE_VAL="${OSTYPE:-}"
    if [[ "$OSTYPE_VAL" == linux* ]]; then
        LINUX_ARCH="$(uname -m)"
        case "$LINUX_ARCH" in
            aarch64|arm64) LINUX_ARCH=arm64;  RUST_TARGET=aarch64-unknown-linux-musl ;;
            *)             LINUX_ARCH=x86_64; RUST_TARGET=x86_64-unknown-linux-musl  ;;
        esac

        echo "Building Linux $LINUX_ARCH release binary (musl static)..."
        cd "$REPO_ROOT"

        if [[ ! -d vendor ]]; then
            echo "  Extracting vendor.tar.xz..."
            tar -xJf vendor.tar.xz
        fi
        mkdir -p .cargo
        cat > .cargo/config.toml <<EOF
[source.crates-io]
replace-with = "vendored-sources"

[source.vendored-sources]
directory = "vendor"

[target.$RUST_TARGET]
linker = "$(command -v musl-gcc 2>/dev/null || echo "musl-gcc")"
EOF
        rustup target add "$RUST_TARGET" 2>/dev/null || true
        cargo build --release --offline --target "$RUST_TARGET" -p oxide-sloc

        ARCHIVE="$DIST/oxide-sloc-linux-${LINUX_ARCH}.tar.gz"
        tar czf "$ARCHIVE" -C "target/$RUST_TARGET/release" oxide-sloc
        echo "  [OK] dist/oxide-sloc-linux-${LINUX_ARCH}.tar.gz"
    else
        echo "  Skipping Linux binary (not on Linux; use a Linux host or cross-compile)"
    fi
fi

# ── Checksums ────────────────────────────────────────────────────────────────
echo "Regenerating dist/checksums.sha256..."
CHECKSUMS="$DIST/checksums.sha256"
{
    printf '# oxide-sloc pre-built binary checksums\n'
    printf '# Generated by scripts/internal/update-dist.sh\n'
    printf '# Verify with: sha256sum -c dist/checksums.sha256\n\n'
    for f in "$DIST"/oxide-sloc-*.{zip,tar.gz} 2>/dev/null; do
        [[ -f "$f" ]] && sha256sum "$f"
    done
} > "$CHECKSUMS"
cat "$CHECKSUMS"

echo ""
echo "Done. Stage and commit:"
echo "  git add dist/"
echo "  git commit -m \"chore: update pre-built binaries v${VERSION}\""
